# Site settings
title: JoeJag Tech - Agile and code
email: joe@joejag.com
description: "Coding and agile blog of Joe Wright"
baseurl: ""
# url: "http://code.joejag.com"
twitter_username: joe_jag
github_username:  joejag

# Build settings
markdown: kramdown
permalink: /:year/:title.html

port: 4001

ftp_host: 'joejag.com'
ftp_dir: '/public_html/code'
ftp_passive: false