# Site settings
title: JoeJag - Tech
email: joeljoejag.com
description: "Coding and agile blog of Joe Wright"
baseurl: ""
url: "http://code.joejag.com"
twitter_username: joe_jag
github_username:  joejag

# Build settings
markdown: kramdown
permalink: pretty

port: 4001
